myapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static
from .views import ContactFormView, ContactResultView
from .admin import mypage_site

app_name = 'myapp'

urlpatterns = [
    # ユーザーマイページ
    path('mypage/', mypage_site.urls),

    path('', views.Index.as_view(), name='index'),
    path('ads.txt', TemplateView.as_view(
                                template_name='myapp/ads.txt', content_type='text/plain'
                             )),  # 追加
    # path('', include('mayapp.urls')),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    # ↓投稿記事の入力内容の確認画面を追加
    # path('post_create_confirm', views.PostCreate.as_view(), name='post_confirm_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    path('post_list', views.PostList.as_view(), name='post_list'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path('category_detail/<str:name_en>', views.CategoryDetail.as_view(), name='category_detail'),
    path('search', views.Search, name='search'),

    # footer links
    path('about', TemplateView.as_view(template_name='myapp/about.html'), name='about'),
    path('terms', TemplateView.as_view(template_name='myapp/terms.html'), name='terms'),
    path('contents_policy', TemplateView.as_view(template_name='myapp/contents_policy.html'), name='contents_policy'),
    path('contact_me', ContactFormView.as_view(), name='contact_me'),
    path('contact_me/contact_result', ContactResultView.as_view(), name='contact_result'),
    # path('policy/', TemplateView.as_view(template_name='base/policy.html'), name='policy'),


]

# print(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

myproject/urls.py
from django.contrib.sitemaps.views import sitemap
from myapp.sitemaps import PostSitemap, StaticSitemap

sitemaps = {
    'post': PostSitemap,
    #'category':BlogCategorySitemap,
    'static': StaticSitemap,    
}


from django.contrib import admin
from django.urls import path, include

admin.site.site_title = 'ぎょうざブログ 内部管理サイト'
admin.site.site_header = 'ぎょうざブログ 内部管理サイト'
admin.site.index_title = 'メニュー'

admin.site.disable_action('delete_selected')



urlpatterns = [
    path('staff-admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.core.files.storage import default_storage
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.
class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category = self).count()
        return n

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('タイトル', max_length=100)
    content = models.TextField('内容', max_length=10000)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    thumbnail_preview = ImageSpecField(source='thumbnail',
                                      processors=[ResizeToFill(200, 100)],
                                      format='PNG',
                                      options={'quality': 60}
                                      )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def like_count(self):
        n = Like.objects.filter(post = self).count()
        return n

    def __str__(self):
        return self.title
    """
    def save(self):
        upload_file = self.files['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        return default_storage.url(file_name)
    """
    @property
    def thumbnail_url(self):
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        return '#'


class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.PROTECT)
    user = models.ForeignKey(User, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)

myapp/forms.py
from django import forms
from .models import Post
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
# from .widgets import FileInputWithPreview

# from django.core.files.storage import default_storage


class  PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('thumbnail', 'title', 'category','content', )
  
    def __init__(self, *args, **kyargs):
        super().__init__(*args, **kyargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    """
    def save(self):
        upload_file = self.files['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        return default_storage.url(file_name)
    """

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kyargs):
        super().__init__(*args, **kyargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2')
        
    def __init__(self, *args, **kyargs):
        super().__init__(*args, **kyargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1, max_length=30, label='', required=False)

    def __init__(self, *args,**kyargs):
        super().__init__(*args,**kyargs)


class ContactForm(forms.Form):
    name = forms.CharField(
        label = '', 
        max_length = 100,
        widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前"
        })
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    inquiry = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['inquiry']
        
        subject = name + "様からのお問い合わせ"
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト

        try:
            send_mail(subject, message, from_email, recipient_list) 

        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

    def clean_message(self):
        message = self.cleaned_data['inquiry']
        if(message.find('<') != -1 or message.find('>') != -1):
            raise forms.ValidationError("恐れ入りますが問い合わせ内容でのタグ利用はお控えください。")
        return message

myapp/views.py
from django.shortcuts import render, resolve_url, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormView
from .models import Post, Like, Category
from django.urls import reverse_lazy
from  .forms import PostForm, LoginForm, SignUpForm, SearchForm, ContactForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True
    def test_func(self):
        post = Post.objects.get(id = self.kwargs['pk'])
        return post.author == self.request.user

def index(request):
    # form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # return redirect(reverse_lazy('myapp:index'))    
    # form = PostForm()
            return render(request, 'myapp/index.html', {'form': form})
    
    
class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data( **kwargs)
        post_list = Post.objects.all().order_by('-created_at')[:9]
        context = {
            'post_list': post_list,
        }
        return context


class  PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    

    def preview(request):
        context_object_name = Post.objects.all()
        return render(request, 'post_form.html',
                      { 'image_list' : context_object_name}
                      )

    # success_url = reverse_lazy('myapp:index')

        
    def get_success_url(self):
        messages.success(self.request, 'Postを新規投稿しました！')
        return resolve_url('myapp:index')
    
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)
    """
        ctx = {'form': form}
        if self.request.POST.get('next', '') == 'confirm':
            return render(self.request, 'myapp/post_confirm_create.html', ctx)
        if self.request.POST.get('next', '') == 'back':
            return render(self.request, 'myapp/post_form.html', ctx)
        if self.request.POST.get('next', '') == 'create':
            return super(PostCreate, self).form_valid(form)
        else:
            # 正常動作ではここは通らない。エラーページへの遷移でも良い
            return redirect(reverse_lazy('myapp:index'))
    """


class PostDetail(DetailView):
    model = Post
    
    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id = self.kwargs['pk'])
        category_posts = Post.objects.filter(category = detail_data.category).order_by('-created_at')
        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, 'Postを更新しました。')
        return resolve_url('myapp:post_detail', pk = self.kwargs['pk'])

    """
    def form_valid(self, form):
        ctx = {'form': form}
        if self.request.POST.get('next', '') == 'confirm':
            return render(self.request, 'myapp/post_confirm_create.html', ctx)
        if self.request.POST.get('next', '') == 'back':
            return render(self.request, 'myapp/post_form.html', ctx)
        if self.request.POST.get('next', '') == 'create':
            return super().form_valid(form)
        else:
            # 正常動作ではここは通らない。エラーページへの遷移でも良い
            return redirect(reverse_lazy('myapp:index'))
    """

class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.warning(self.request, 'Postを削除しました。')
        return resolve_url('myapp:index')


class PostList(ListView):
    model = Post
    paginate_by = 7

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'


class Logout(LogoutView):
    template_name = 'myapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.info(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())

@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id = post_id)
    is_liked = Like.objects.filter(user = request.user, post = post_id).count()
    if is_liked > 0:
        messages.info(request, 'すでにお気に入りに追加済みです。')
        return redirect('myapp:post_detail', post_id)

    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, "お気に入りを追加しました！")
    return redirect('myapp:post_detail', post.id)


class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en' 

    def get_context_data(self, * args, **kwargs):
        detail_data = Category.objects.get(name_en = self.kwargs['name_en'])
        category_posts = Post.objects.filter(category = detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = Post.objects.filter(Q(title__icontains = freeword) | Q(content__icontains = freeword))

        params = {
            'search_list': search_list,
        }
        # print("search active!")
        return render(request, 'myapp/search.html', params)


class ContactFormView(FormView):
    template_name = 'myapp/contact_me.html'
    form_class = ContactForm
    success_url = reverse_lazy('myapp:contact_result')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class ContactResultView(TemplateView):
    template_name = 'myapp/contact_result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['success'] = "お問い合わせは正常に送信されました。"
        return context

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-202046552-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-202046552-1');
    </script>
    <!-- Global site tag (gtag.js) - Google AdSense -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6237837293601032"
     crossorigin="anonymous"></script>
    
    <!-- Global site tag (gtag.js) - Google AMP site
    <script async custom-element="amp-auto-ads"
    src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
    </script>
    -->

    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon-180x180_.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon_.ico' %}">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{{ request.site.siteconfig.meta_title }}{% endblock %}</title>
    <meta name="description" content="{{ request.site.siteconfig.meta_description }}"> 
    <meta name="keywords" content="{{ request.site.siteconfig.meta_keyword }}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

    <!-- Your custom styles (optional) -->
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    
    <!-- Facebook, Twitter共通 -->
    <meta property="og:title" content="{{ object.title }}">
    <meta property="og:type" content="article">
    <meta property="og:description" content="{{ object.content }}">
    {% if object.thumbnail %}
    <meta property="og:image" content="{{ object.thumbnail.url }}">
    {% endif %}
    <!-- Facebook:カード用 -->

    <!-- Twitter:カード用 -->
    <meta name="twitter:card" content="summary">
    {% if object.thumbnail %}
    <meta name="twitter:image" content="{{ object.thumbnail.url }}">
    {% endif %}

</head>

<body>
    <!-- Global site tag (gtag.js) - Google AMP site
    <amp-auto-ads type="adsense"
        data-ad-client="ca-pub-6237837293601032">
    </amp-auto-ads>
     -->
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark purple">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="/">ぎょうざブログ</a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myapp:index'%}"><i class="fas fa-home"></i>ホーム<span class="sr-only">(current)</span>

                    </a>
                </li>

                <!-- Dropdown -->
                {% if request.user.is_active %}                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="account" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"><i class="fas fa-user-circle"></i>アカウント</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="account">
                            {% if request.user.is_authenticated %}
                            <a class="dropdown-item">{{ request.user }}</a>
                            <a class="dropdown-item" href="{% url 'myapp:logout' %}">ログアウト</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'myapp:login' %}">ログイン</a>
                            <!--
                                    <a class="dropdown-item" href="{% url 'myapp:signup' %}">ユーザー登録</a>
                                -->
                            {% endif %}

                    </div>      
                </li>
                {% endif %}

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false"><i class="fas fa-newspaper"></i>投稿</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.user.is_active %} 
                        <a class="dropdown-item" href="{% url 'myapp:post_create'%}"><i class="bi bi-file-earmark-post"></i>新規投稿</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'myapp:post_list'%}">投稿一覧</a>


                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-tags"></i>カテゴリー</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        {% for item in category_list %}
                        <a class="dropdown-item" href="{% url 'myapp:category_detail' item.name_en %}">{{ item.name }}</a>
                        {% endfor %}
                        <hr>
                        <a class="dropdown-item" href="{% url 'myapp:category_list' %}">カテゴリ一覧</a>
                    </div>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a href="/staff-admin/" class="nav-link waves-light" mdbWavesEffect>
                        <i class="fas fa-user-cog"></i>管理画面</a>
                </li>
                {% endif %}

            </ul>
            <!-- Links -->

            <form action="{% url 'myapp:search' %}" class="form-inline" method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" ,
                    name="freeword">

            </form>
        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->


    <main class='container'>
        {% if messages %}
        <br>
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </main>


    <!-- Footer -->
    <footer class="page-footer font-small purple pt-4">

        <!-- Footer Links -->
        <div class="container-fluid text-center text-md-left">

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-6 mt-md-0 mt-3">

                    <!-- Content -->
                    <div class="caution_contents">
                        <h5 class="text-uppercase"><b>注意事項</b></h5>

                        <p>当サイトでは、アクセス解析のため「Googleアナリティクス」を使用しています。</p>
                        <p>このGoogleアナリティクスはデータの収集のためにCookieを使用しています。</p>
                        <p>このデータは匿名で収集されており、個人を特定するものではありません。</p>
                        <p>この機能はCookieを無効にすることで収集を拒否することが出来ますので</p>
                        <p>お使いのブラウザの設定をご確認ください。</p>
                        <p>この規約に関しての詳細は<a
                                href="https://marketingplatform.google.com/about/analytics/terms/jp/"><u>Googleアナリティクスサービス利用規約</u></a>や
                            <a
                                href="https://policies.google.com/technologies/ads?hl=ja"><u>Googleポリシーと規約</u></a>をご覧ください。
                        </p>
                    </div>
                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">

                <!-- Grid column -->
                <div class="col-md-6 mb-md-0 mb-3">

                    <!-- Links -->
                    <h5 class="text-uppercase">リンク集</h5>

                    <ul class="list_footer">
                        <li>
                            <a href="{% url 'myapp:about' %}"><u>サイト概要</u></a>
                        </li>
                        <li>
                            <a href="{% url 'myapp:terms' %}"><u>利用規約</u></a>
                        </li>
                        <li>
                            <a href="{% url 'myapp:contents_policy' %}"><u>コンテンツポリシー</u></a>
                        </li>
                        <li>
                            <a href="{% url 'myapp:contact_me' %}"><u>お問い合わせ</u></a>
                        </li>
                    </ul>

                </div>
                <!-- Grid column -->

                <!-- Grid column 
                <div class="col-md-3 mb-md-0 mb-3">

                     Links 
                    <h5 class="text-uppercase">Links</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a href="#!">Link 1</a>
                        </li>
                        <li>
                            <a href="#!">Link 2</a>
                        </li>
                        <li>
                            <a href="#!">Link 3</a>
                        </li>
                        <li>
                            <a href="#!">Link 4</a>
                        </li>
                    </ul>

                </div>
                Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2021 Copyright:
            <a href="https://udemy-django-4180.herokuapp.com/"> World-Hacker.com</a>
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->



    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    <!-- Facebook -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v12.0" nonce="pLOMyQwS"></script>

    <!-- Twitter -->
    <script>window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
          t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);
      
        t._e = [];
        t.ready = function(f) {
          t._e.push(f);
        };
      
        return t;
      }(document, "script", "twitter-wjs"));</script>

    <!-- Pinterest -->
    <script async defer src="//assets.pinterest.com/js/pinit.js"></script>
    
</body>

</html>

myapp/templates/myapp/category_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <br>
        <h2>カテゴリ一覧</h2>
        <hr>
        <br>
    </div>
</div>
<div class="row">
    {% for category in category_list %}
    
    <div class="col-md-4">
        <div class="section1">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'myapp:category_detail' category.name_en %}">{{ category.name }}</a>&nbsp;<small>[&nbsp;{{ category.post_count }}&nbsp;]</small></h4>
                <hr>
                    {% for post in category.post_set.all|slice:":5" %}
                    <p><a href="{% url 'myapp:post_detail' post.id %}" style="color:black; border-bottom: solid 1px purple;">{{ post.title }}</a></p>
                    {% endfor %}
                    <br>
                    <a class = "btn btn-primary"  id="category_list" href="{% url 'myapp:category_detail' category.name_en %}">このカテゴリの記事をすべて見る</a>

            </div>
        </div>
        </div>
        <br>
        
    </div>
    
    {% endfor %}
    
    </div>
    <br>
</div>

{% endblock %}

myapp/templates/myapp/contact_result.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="ui breadcrumb">
    <a href="{% url 'myapp:index' %}" class="section">ホーム</a>
    <span class="divider">　▶　</span>
    <a class="active section">お問い合わせ</a>
</div>
{{ success }}
<br>
<br>
<br>
<br>
<br>
{% endblock %}